var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxx              xxxxxxxx               xxxxxxxx                  xxxxxxxxx",
   "xxxxxxx                xxxxxx                 xxxxxx                    xxxxxxxx",
   "xxxxxx                  xxxx                   xxxx                       xxxxxx",
   "xxxxx                    xx                     xx                         xxxxx",
   "xxxx                                                    o      o  =o   o    xxxx",
   "xxx                                                            xxxxxxxxx     xxx",
   "xx o                                          o        xx       x!!!!!x       xx",
   "xxxxxx                              o o      xx    o             x!!!x         x",
   "x                                                                xx!xx         x",
   "x o o                                xxxx  |     |xx    |         xvx          x",
   "xo o                                                                           x",
   "xxxxxxx                                   o o                                  x",
   "xxxxxxx         xxxxxxxx   xxxxxxxx                                            x",
   "x             xxxxxxxx    xxxxxxxxxx     xxxxx                    o o          x",
   "xx                x!!x  o                    x                   xxxxxx        x",
   "xxx  @            x!!x  x  o o               x =   o         o  =x          xxxx",
   "xxxxxxxxxxxxxx    x!!x     xxx    xxxxxxxx   xxxxxxxxx     xxxxxxx          x  x",
   "xxxxxxxxxxxxxx    x!!x            x!!!!!!x   x!!!!!!!x     x                x  x",
   "!!!!!!!!!!!!!x!!!!x!!x   =    =  xx!!!!!!xx  x!!!!!!!x!!!!!x       o        x  x",
   "!!!!!!!!!!!!!x!!!!x!!xxxxxxxxxxxxxx!!!!!!x |ox!!!!!!!x!!!!!x       x    xxxxx  x",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  xx!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xooxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxx                               xxx!!!xxx                     xx!!!xx                                   xxxxxx",
   "xxxx                                 xx!!!xx                       xx!xx                                     xxxxx",
   "xxx                                   xx!xx                         xvx                                       xxxx",
   "xx                                     xvx                                                                     xxx",
   "x                                                                                                               xx",
   "x                                                                x!!!!!!!x                                       x",
   "x                          x     x                                xvxxxvx                                        x",
   "x                          xo    xx  xxx!xxxxxxx                    xxx                                          x",
   "x                          xxx   x  ox!!!xxxxxxx    o                 o                                          x",
   "x                          x    ox  xx!xxxxxxxxx   xxx                                                           x",
   "x                          x    xxo  x!!!!!!!!!x     x               o                                           x",
   "x                          xo    xx  xxxxxxxxx!x     x                                                           x",
   "x                          xxx   x  ox!!!!!!!!!xo    x                o    x                                     x",
   "x                          x    ox  xx!xxxxxxxxxxx   x                =    x                                     x",
   "x                          x    xx   x!!!!!!!!!x     x      o  o   xxxxxxxxx   o   o x                           x",
   "x                          x o   xo  xxxxxxxxx!x     x       =                       x                           x",
   "xx                         xxxx  x   x!!!!!!!!!x    ox     xxxxxx            xxxxxxxxx                           x",
   "xxx                              xo xx!xxxxxxxxx   xxx                       x                                   x",
   "xxxx @    o    o    o            x   x!!!!!!!!!x     x                    o  x                                   x",
   "xxxxxxx   x    x    x   xxxxxxxxxxo  xxxxxxxxx!x     x                   xxxxx   xxxx                            x",
   "xxxxxxx                 x!!!!!xxxx   x!!!!!!!!!xo    x  o  o               o     x!!x                            x",
   "!!!!!!x                 x!!!!!xx  o xxx!!!!!!!xxxx      x  x               =    xx!!x                            x",
   "!!!!!!x!!!!!!!!!!!!!!!!!x!!!!!xx      xxxxvxxxxx                  xxxxxxxxxxxxxxxx!!x  o o                       x",
   "!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!xx       xxx xxx      xxx!!!!!xx!!!!!!!!!!!!!!!!!!!!!!xx          o    o    o   o  x",
   "!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!xxx               o  xx!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx    x    x    x   x  x",
   "!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!xxxx   x         xxxxx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!xxxxxxxxxx  o  xxxxxxx!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxx o o o o             xx!xx       xx!!!xx                 x!!!!!!!x                                 xxxxxxx",
   "xxxx o o o o              xvx         x!!!x                   x!!!!!x                                   xxxxxx",
   "xxxxxxxxxxxxxxxo                      x!!!x                    x!!!x                                     xxxxx",
   "xxxxxxxxxxxxxxxx                      x!!!x o  o                xvx                                        xxx",
   "xxxxxxxxxxxxxxxxx                     x!!!xx o  o                            o                              xx",
   "xxxxxxxxxxxxxxxxxx0                   x!!!xxxxxxxx      o  o                xxx                              x",
   "xxxxxxxxxxxxxxxxxxx                   x!!!x           xxxxxxxx             x!!!x                             x",
   "xxxxxxxxxxxxxxxxxxxxo                 x!!!x           x                     xvx                              x",
   "xxxxxxxxxxxxxxxxxxxxx                 x!!!xx         ox             o                                        x",
   "!!!!!!!!!!!!!!!!!!!xxx                x!!!x=     =  xxx            xxx                                       x",
   "!!!!!!!x!x!!x!!!xx!!xxx               x!!!x      o    x           x!!!x       o                              x",
   "!!!!!!xxxx!xxx!xxxxx!xxx              x!!!x      =    x      o     xvx       xxx                             x",
   "xxxxxxx  xvx xvx   xvx xx              xvx      xx    x      @              x!!!x        o                   x",
   "xxxxxx                  xx                            x      x               xvx        xxx                  x",
   "xxxxx                                                 x              xx                x!!!x                 x",
   "xxxx                        xxxxxx               o o  x!!!!!!!!!!!!!!xo                 xvx                  x",
   "xxx                         xx                        xx!!!!!!!!!!!!xx                                       x",
   "xx                           x                 xxxxxxxxxxxxxxxxxxxxxxxx               o                      x",
   "x        o  o  o  o  o  xxx  x=     o    xxx                                         xxx                     x",
   "x        x  x  x  x  x       x     xx     x                                         x!!!x                    x",
   "x                            x            x o o                           o o        xvx                     x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x            xxxxxxx                        xxxxx                               x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x            x                              x!!!x                               x",
   "xx!!!!!!!!!!!!!!!!!!!!!!!!!!xx           xx         o o       o o        x!!!x                               x",
   "xxxxxxx!xxxxxx!xxxxxxxx!xxx!xx=   o       x       |xxxx|    |xxxx|     xxx!!!x     o                         x",
   "xxxx  xvx    xvx      xvx xvx     xx     x                              x!!!!x     xxx                       x",
   "xxx                                       x                             x!!!!x    x!!!x                     xx",
   "xx                  |                     x                             x!!!!x     xvx                     xxx",
   "xx                            xx!xx!xx!xx!x                            xx!!!!x                            xxxx",
   "xxx    o      o  |     o   o  x           x!!x oo x!!!!x oo x!!!!x oo xx!!!xx                            xxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxx!!!!xxxxxx!!!!xxxxxx!!!!!xx                          xxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "xxxxxxxx                                                           xxxxxxxxx",
  "xxxxxxx                                                             xxxxxxxx",
  "xxxxxx                               @                                xxxxxx",
  "xxxxx                                                                  xxxxx",
  "xxxx                                                                    xxxx",
  "xxx                                                                      xxx",
  "xx                                                                        xx",
  "x                  x   x  xxxx  x  x   x   x  xxxx  xx  x                  x",
  "x                  xxxxx  x  x  x  x   x x x   xx   x x x                  x",
  "x                    x    xxxx  xxxx   xxxxx  xxxx  x  xx                  x",
  "x                                                                          x",
  "x                                                                          x",
  "x                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 x",
  "x                                                                          x",
  "x                                                                          x",
  "x                                                                          x",
  "x                                                                          x",
  "x                                                                          x",
  "!                                                                          x",
  "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
  "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
  "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
  "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
];

if (typeof module !== "undefined" && module.exports)
  module.exports = GAME_LEVELS;
